# -*- coding: utf-8 -*-
"""Task7_Sales_Summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RJvW2rwUY41wfmkeJ80GaGLFI4UKVJs
"""

import sqlite3

# Step 1: connect or create the database file
conn = sqlite3.connect("sales_data.db")
cur = conn.cursor()

# Step 2: create a table
cur.execute("""
CREATE TABLE IF NOT EXISTS sales(
    date TEXT,
    order_id INTEGER,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# Step 3: insert few rows
rows = [
    ("2025-10-01",1001,"Notebook",2,120.00),
    ("2025-10-02",1002,"Pen",10,5.00),
    ("2025-10-03",1003,"Notebook",1,120.00),
    ("2025-10-03",1004,"Backpack",1,800.00),
    ("2025-10-04",1005,"Pen",5,5.00)
]
cur.executemany("INSERT INTO sales VALUES(?,?,?,?,?)", rows)
conn.commit()
conn.close()

print("✅ sales_data.db created successfully!")

import pandas as pd
import sqlite3

conn = sqlite3.connect("sales_data.db")

query = """
SELECT product,
       SUM(quantity) AS total_quantity,
       SUM(quantity*price) AS revenue
FROM sales
GROUP BY product
ORDER BY revenue DESC
"""
df = pd.read_sql_query(query, conn)
conn.close()

print("📊 Sales Summary:")
print(df)

import matplotlib.pyplot as plt

df.plot(kind="bar", x="product", y="revenue", legend=False)
plt.title("Revenue by Product")
plt.ylabel("Revenue")
plt.tight_layout()
plt.sagvefig("sales_chart.png")
plt.show()